# Generated by Django 5.2.4 on 2025-07-29 23:49

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkeychat', '0007_alter_chatgroup_group_name_alter_groupmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
