# Generated by Django 5.2.4 on 2025-08-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkeyusers', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_avatar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
